# Site settings
title: ifziv's blog
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: Learn from yesterday, live for today, hope for tomorrow.

# Social icons
#facebook: username
#linkedin: username
github: ifziv
email: username
#deviantart: username
#codepen: username

footer: © ifziv

# Build settings
markdown: kramdown
